[versions]
serialization = "1.3.2"
exposed = "0.38.2"
kotlin = "1.6.10"
coroutines = "1.6.1"
ktor = "2.0.1"
koin = "3.1.6"
kotest = "5.2.3"
mccoroutine = "2.1.0"
fawe = "2.4.3"

[libraries]
minecraft-headlib = "com.github.DRE2N.HeadLib:headlib-core:877e80d3b3"
minecraft-headlib-core = "de.erethon:headlib:3.0.10"
minecraft-mccoroutine = { module = "com.github.shynixn.mccoroutine:mccoroutine-bukkit-api", version.ref = "mccoroutine" }
minecraft-mccoroutine-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-bukkit-core", version.ref = "mccoroutine" }
minecraft-anvilgui = "net.wesjd:anvilgui:1.5.3-SNAPSHOT"
minecraft-mockbukkit = "com.github.seeseemelk:MockBukkit-v1.18:1.24.1"

minecraft-plugin-modelengine = "com.ticxo.modelengine:api:R2.5.0"
minecraft-plugin-protocollib = "com.comphenix.protocol:ProtocolLib:5.0.0-SNAPSHOT"
minecraft-plugin-fawe-core = { module = "com.fastasyncworldedit:FastAsyncWorldEdit-Core", version.ref = "fawe" }
minecraft-plugin-fawe-bukkit = { module = "com.fastasyncworldedit:FastAsyncWorldEdit-Bukkit", version.ref = "fawe" }
minecraft-plugin-vault = "com.github.MilkBowl:VaultAPI:1.7"
minecraft-plugin-worldguard = "com.sk89q.worldguard:worldguard-bukkit:7.1.0-SNAPSHOT"

fastutil = "it.unimi.dsi:fastutil:8.2.2"
reflections = "org.reflections:reflections:0.9.12"

exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-javatime = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
sqlite-jdbc = "org.xerial:sqlite-jdbc:3.36.0.2"

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "serialization" }
kotlinx-serialization-hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }
kotlinx-serialization-properties = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties", version.ref = "serialization" }
kotlinx-serialization-kaml = "com.charleskorn.kaml:kaml:0.43.0"

kotlin-statistics = "org.nield:kotlin-statistics:1.2.1"

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5", version.ref = "koin" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }

ktor-serialization = { module = "io.ktor:ktor-serialization", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }

logback-classic = "ch.qos.logback:logback-classic:1.2.3"
kmongo-coroutine-serialization = "org.litote.kmongo:kmongo-coroutine-serialization:4.3.0"

mockk = "io.mockk:mockk:1.12.3"
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }

junit-bom = "org.junit:junit-bom:5.8.2"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

[bundles]
minecraft = ["minecraft-headlib", "minecraft-mccoroutine", "minecraft-anvilgui"]
exposed = ["exposed-core", "exposed-dao", "exposed-jdbc", "exposed-javatime", "sqlite-jdbc"]
