[versions]
anvilgui = "1.10.3-SNAPSHOT"
compose = "1.8.2"
coroutines = "1.10.2"
# @pin
creative = "1.11.8"
customblockdata = "2.2.4"
dataframe = "0.15.0"
dependencyversions = "0.52.0"
dokka = "2.1.0"
exposed = "1.0.0-beta-3"
fastutil = "8.5.18"
fawe = "2.14.3"
java = "21"
junit = "5.12.0"
jvm-for-kotlin-multiplatform = "21"
kaml = "0.104.0"
kotest = "6.0.7"
# ENSURE KOTLIN MATCHES THE VERSION IN GRADLE-CONVENTIONS REPO.
# @pin
kotlin = "2.3.0"
kotlinxIO = "0.8.2"
logback = "1.5.23"
mccoroutine = "2.22.0"
# @pin
minecraft = "1.21.11-R0.1-SNAPSHOT"
mockbukkit = "4.64.0"
mockk = "1.14.7"
modelengine = "R4.1.0"
morepersistentdatatypes = "2.4.0"
mythic-dist = "5.11.0"
mythiccrucible = "2.4.0-SNAPSHOT"
nexo = "1.17.0"
reflections = "0.10.2"
serialization = "1.10.0-RC"
shadowjar = "9.3.0"
sqlite-jdbc = "3.50.2.0"
sqlite = "2.5.2"
vault = "1.7"
version-catalog-update = "1.0.0"
worldguard = "7.1.0-SNAPSHOT"

[libraries]
creative-api = { module = "team.unnamed:creative-api", version.ref = "creative" }
creative-serializer-minecraft = { module = "team.unnamed:creative-serializer-minecraft", version.ref = "creative" }
creative-server = { module = "team.unnamed:creative-server", version.ref = "creative" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-javatime = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
kermit = "co.touchlab:kermit:2.0.5"
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-dataframe = { module = "org.jetbrains.kotlinx:dataframe-core", version.ref = "dataframe" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIO" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "serialization" }
kotlinx-serialization-hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-serialization-kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
kotlinx-serialization-properties = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties", version.ref = "serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
minecraft-anvilgui = { module = "net.wesjd:anvilgui", version.ref = "anvilgui" }
minecraft-customblockdata = { module = "com.jeff-media:custom-block-data", version.ref = "customblockdata" }
minecraft-mccoroutine = { module = "com.github.shynixn.mccoroutine:mccoroutine-bukkit-api", version.ref = "mccoroutine" }
minecraft-mccoroutine-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-bukkit-core", version.ref = "mccoroutine" }
minecraft-mockbukkit = { module = "org.mockbukkit.mockbukkit:mockbukkit-v1.21", version.ref = "mockbukkit" }
minecraft-morepersistentdatatypes = { module = "com.jeff-media:MorePersistentDataTypes", version.ref = "morepersistentdatatypes" }
minecraft-papermc = { module = "io.papermc.paper:paper-api", version.ref = "minecraft" }
#minecraft-cartridge = { module = "com.mineinabyss.cartridge:cartridge-api", version.ref = "minecraft" }
minecraft-plugin-fawe-bukkit = { module = "com.fastasyncworldedit:FastAsyncWorldEdit-Bukkit", version.ref = "fawe" }
minecraft-plugin-fawe-core = { module = "com.fastasyncworldedit:FastAsyncWorldEdit-Core", version.ref = "fawe" }
minecraft-plugin-modelengine = { module = "com.ticxo.modelengine:ModelEngine", version.ref = "modelengine" }
minecraft-plugin-mythic-dist = { module = "io.lumine:Mythic-Dist", version.ref = "mythic-dist" }
minecraft-plugin-nexo = { module = "com.nexomc:nexo", version.ref = "nexo" }
minecraft-plugin-vault = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
minecraft-plugin-worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

[bundles]
exposed = [
    "exposed-core",
    "exposed-dao",
    "exposed-javatime",
    "exposed-jdbc",
    "sqlite-jdbc",
]
minecraft = [
    "minecraft-anvilgui",
]
platform = [
    "androidx-sqlite-bundled",
    "creative-api",
    "creative-serializer-minecraft",
    "creative-server",
    "kermit",
    "kotlin-reflect",
    "kotlin-stdlib",
    "kotlinx-coroutines",
    "kotlinx-io",
    "kotlinx-serialization-cbor",
    "kotlinx-serialization-hocon",
    "kotlinx-serialization-json",
    "kotlinx-serialization-kaml",
    "kotlinx-serialization-properties",
    "kotlinx-serialization-protobuf",
    "logback-classic",
    "minecraft-anvilgui",
    "minecraft-customblockdata",
    "minecraft-mccoroutine-core",
    "minecraft-morepersistentdatatypes",
    "reflections",
]

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dependencyversions = { id = "com.github.ben-manes.versions", version.ref = "dependencyversions" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadowjar = { id = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadowjar" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
