name: Publish Packages

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - id: repoversion
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}

      - name: Set env variable from version received
        run: echo "RELEASE_VERSION=${{ steps.repoversion.outputs.release }}" >> $GITHUB_ENV

      - name: Run gradle build and publish
        run: >
          gradle build publish
          -PmineinabyssMavenUsername=${{ secrets.MAVEN_PUBLISH_USERNAME }} -PmineinabyssMavenPassword=${{ secrets.MAVEN_PUBLISH_PASSWORD }}

      - name: Check whether the gradle platform has been updated
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            platform:
              - 'idofront-catalog/**'
              - 'idofront-catalog-shaded/**'
              - '**/libs.versions.toml'

      - name: Get version from gradle
        if: steps.changes.outputs.platform == 'true'
        shell: bash
        id: extract_version
        run: |
          version=`gradle properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}'`
          echo "::set-output name=version::$version"

      - name: Create GitHub Release for shaded idofront platfrom
        if: steps.changes.outputs.platform == 'true'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: v${{ steps.extract_version.outputs.version }}
          files: |
            idofront-catalog-shaded/build/libs/*.platform


