name: Publish Packages

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

concurrency: publish-packages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: MineInAbyss/publish-action@master
        with:
          maven-metadata-url: https://repo.mineinabyss.com/releases/com/mineinabyss/conventions/kotlin/jvm/com.mineinabyss.conventions.kotlin.jvm.gradle.plugin/maven-metadata.xml
          maven-username: ${{ secrets.MAVEN_PUBLISH_USERNAME }}
          maven-password: ${{ secrets.MAVEN_PUBLISH_PASSWORD }}

      - name: Check whether the gradle platform has been updated
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            platform:
              - 'idofront-catalog/**'
              - 'idofront-catalog-shaded/**'
              - '**/libs.versions.toml'

      - name: Get version from gradle
        if: steps.changes.outputs.platform == 'true'
        shell: bash
        id: extract_version
        run: |
          version=`gradle properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}'`
          echo "::set-output name=version::$version"

      - name: Create GitHub Release for shaded idofront platfrom
        if: steps.changes.outputs.platform == 'true'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: v${{ steps.extract_version.outputs.version }}
          files: |
            idofront-catalog-shaded/build/libs/*.platform


